apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloudevents-go
spec:
  template:
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: FNHOST
          value: "cloudevents-spring-boot.default.example.com"
        - name: FNHOST
          value: "http://knative-external-proxy.gloo-system.svc.cluster.local"