apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloudevents-go
spec:
  template:
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        # Uncomment this to send events somewhere.
         env:
         - name: K_SINK
           value: http://cloudevents-java.default.example.com
